- hosts: ec2-instances
  become: true
  tasks:
    - name: Copy a file
      copy:
        src: /Users/Leela/Desktop/AWS/copied.png
        dest: /home/ec2-user/copied2.png
        owner: unixadm
        group: root
        mode: 0777
      when: ansible_distribution == 'Ubuntu'
