- hosts: ec2-instances
  become: true
  vars:
    remote_dir: /etc/ansible
    source_file: /Users/Leela/Desktop/AWS/sample.txt
  - name: Creates Remote Directory
    file:
      state: directory
      recurse: yes
      path: "{{remote_dir}}"
  - name: copy file to remote host
    copy:
      src: "{{source_file}}"
      dest: "{{remote_dir}}"

