- hosts: ec2-instances
  become: true
  vars:
    mail_services:
      - postfix
      - dovecot
  tasks:
    - name: Install Postfix and dovecot
      yum:
        name: "{{item}}"
        state: latest
      with_items: "{{mail_services}}"

