- hosts: ec2-instances
  become: true
  vars:
    httpd_pkg: httpd
    firewalld_pkg: firewalld
    httpd_service: httpd
    firewalld_service: firewalld
    rule: http
  tasks:
    - name: Install Latest Version of {{httpd_pkg}} Pakage
      yum:
        name: "{{httpd_pkg}}"
        state: latest
    - name: Start and enable {{httpd_service}} Service
      service:
        name: "{{httpd_service}}"
        state: started
        enabled: true
    - name: Install {{firewalld_pkg}} pakage
      yum:
        name: "{{firewalld_pkg}}"
        state: latest
    - name: Start and enable {{firewalld_service}} Service
      service:
        name: "{{firewalld_service}}"
        state: started
        enabled: true
    - name: open port for {{rule}}
      firewalld:
        service: "{{rule}}"
        state: enabled
        immediate: yes
        permanent: true
    - name: create a html web page
      copy:
        dest: /var/www/html/index.html
        content: "Welcome!!!"
